### ISSUE TITLE
Is the port configurable?

### ISSUE THREAD

**Issue by mbigras** [prometheus-net/docker_exporter#6]
Thank you very much for this exporter, I've been using it and it works great!

I have a question about the port that the exporter listens on. From looking at:

https://github.com/prometheus-net/docker_exporter/blob/fe7d3ad24246f3a6fc721454e5add15687333960/ExporterLogic.cs#L36

It looks like the port is hard-coded to 9417 and it doesn't seem like that's configurable. Is there a way to configure the port using something like the `PORT` environment variable?

**Comment by sandersaares** [comment]
As the exporter is designed to run inside a container, you can simply do the port change using `--publish 1234:5678` syntax when starting the Docker container, using different external/internal ports. Does this satisfy your need?

**Comment by mbigras** [comment]
Aha smart! Yes that works 👍
